### ISSUE TITLE
Optionally, do not clear cache on AJAX error

### ISSUE THREAD

**Issue by thinkdj** [SaneMethod/jquery-ajax-localstorage-cache#38]
I am using it for a hybrid desktop app and sometimes the client is offline. AJAX fails and the cache is cleared. It would be great to have an option to keep the earlier contents till a successful fetch happens.

**Comment by SaneMethod** [comment]
This should already be the case. Once a value is stored in the localCache, the next request will return the value from the cache - no request to the server is carried out in this case, so being offline shouldn't affect anything.

I suggest confirming that your case doesn't involve a change to the generated/specified cacheKey in the ajax request parameters, and that the behaviour you're seeing isn't caused by the expected clearing of items once they've exceeded the default/specified time-to-live.

**Comment by thinkdj** [comment]
Apologies (for the issue and also for reverting so late) 
The cache had expired when I was trying it out.
