### ISSUE TITLE
cacheKey sometimes generates poorly

### ISSUE THREAD

**Issue by gedeminas** [SaneMethod/jquery-ajax-localstorage-cache#39]
Didn't have lots of time to investigate, but when using jQuery 1.11.3, genCacheKey() generates different keys when storing and getting the cached object and plugin doesn't work correctly.
That could be because of options.url difference in the function, in one place it looks like pure url, in other like url + params already.

Anyway thanks for your great work!

**Comment by SaneMethod** [comment]
Thanks gedeminas. I'll need more information to be able to diagnose the issue here - if you could link to an example, that would be helpful.

**Comment by gedeminas** [comment]
Well, i just use your plugin simple like this:
`$.ajax({
          url: 'data.php',
          data: {
            'a': a,
            'b': b
          },
          dataType: 'text',
          localCache: true,
          cacheTTL: 1,
          cacheKey: 'a-' + a + '-b-' + b, // cache doesn't work if cacheKey generates automatically because of options.url
          type: 'GET'
        }).done(function(data){`

So if I leave cacheKey to generate automatically here, it comes out different compared to the one, which plugin uses trying to get cached object. I tried to investigate the plugin and found that options.url adds data params in different places of url somehow. I hope that's enough information for you to understand.

**Comment by johnv-git** [comment]
The default cacheKey generation fails for GET requests because the options url/data pair is mutated between the call to ajaxPrefilter and ajaxTransport.

In ajaxPrefilter():
options.type = GET
options.url = /path/to/api/method
options.data = p1=param1&p2=param2

In ajaxTransport():
options.type = GET
options.url = /path/to/api/method?p1=param1&p2=param2&_=1489431445387
options.data = undefined

So the default cacheKey of (url + type + data) yields:
ajaxPrefilter => /path/to/api/methodGETp1=param1&p2=param2
ajaxTransport => /path/to/api/method?p1=param1&p2=param2GET

This cacheKey function works nicely for both GET and POST requests.
`return options.cacheKey || options.type + url + (options.data ? '?' + options.data : '');`
